# Generated by Django 5.0.6 on 2024-09-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FixWayApp', '0003_alter_inventario_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='ano_producto_uso_fin',
            new_name='anoProductoUsoFin',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='ano_producto_uso_inicio',
            new_name='anoProductoUsoInicio',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_producto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='marca_automovil',
            new_name='marcaAutomovil',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='marca_producto',
            new_name='marcaProducto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre_producto',
            new_name='nombreProducto',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='precio_detalle',
            new_name='precioDetalle',
        ),
    ]
