# Generated by Django 5.0.6 on 2024-09-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('ano_producto_uso_fin', models.CharField(max_length=4)),
                ('ano_producto_uso_inicio', models.CharField(max_length=4)),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('codigo_producto', models.CharField(max_length=10)),
                ('costo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca_automovil', models.CharField(max_length=255)),
                ('marca_producto', models.CharField(max_length=255)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=255)),
                ('precio_detalle', models.IntegerField()),
            ],
        ),
    ]
