# Generated by Django 5.0.6 on 2024-09-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixWayApp', '0002_remove_inventario_codigo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_producto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
